PlaceSite/PlaceSite/Models/CafeClass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PlaceSite.Models
{
    public class CafeClass
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string Type { get; set; }

        public ICollection<Cafe> Cafes { get; set; }

    }
}

PlaceSite/PlaceSite/Models/HotelClass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PlaceSite.Models
{
    public class HotelClass
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string Type { get; set; }

        public ICollection<Hotel> Hotels { get; set; }
    }
}

PlaceSite/PlaceSite/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PlaceSite.Models
{
    public class Menu
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string FoodName { get; set; }
        [StringLength(200)]
        public string Explanation { get; set; }
        public int Price { get; set; }

        public ICollection<Menu> Menus { get; set; }

    }
}

PlaceSite/PlaceSite/Models/Price.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PlaceSite.Models
{
    public class Price
    {

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string RoomName { get; set; }
        public int RoomPrice { get; set; }
        public ICollection<Hotel> Hotels { get; set; }
        public virtual Price Pricess { get; set; }

    }
}

PlaceSite/PlaceSite/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PlaceSite.Models;

namespace PlaceSite.Controllers
{
    public class AdminPanelController : Controller
    {
        Context c = new Context();
        // GET: Admin
        public ActionResult Index(string p)
        {
            var list = from x in c.Admins select x;
            if (!string.IsNullOrEmpty(p))
            { list = list.Where(y => y.UserName.Contains(p)); }
            return View(list.ToList());
        }

        [HttpGet]
        public ActionResult AdminAdd()
        {
            List<SelectListItem> value1 = (from x in c.Admins.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UserName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            return View();
        }
        [HttpPost]
        public ActionResult AdminAdd(Admin p)
        {
            c.Admins.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AdminDelete(int id)
        {
            var value = c.Admins.Find(id);
            
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AdminUpgrade(int id)
        {
            List<SelectListItem> value1 = (from x in c.Admins.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UserName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            var values = c.Admins.Find(id);
            return View("AdminUpgrade", values);
        }

        public ActionResult AdminUpdate(Admin p)
        {
            var admin = c.Admins.Find(p.Id);
            admin.UserName = p.UserName;
            admin.Password = p.Password;
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        // About
     

      
        public ActionResult AboutUpgrade(int id)
        {
            List<SelectListItem> value1 = (from x in c.Abouts.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.AboutUs,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            var values = c.Abouts.Find(id);
            return View("AboutUpgrade", values);
        }

        public ActionResult AboutUpdate(About p)
        {
            var about = c.Abouts.Find(p.Id);
            about.AboutUs = p.AboutUs;
            about.Img = p.Img;
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        // cafe
        public ActionResult CafeInfo(string p)
        {
            var list = from x in c.Cafes select x;
            if (!string.IsNullOrEmpty(p))
            { list = list.Where(y => y.CafeName.Contains(p)); }
            return View(list.ToList());
        }

        [HttpGet]
        public ActionResult CafeAdd()
        {
            List<SelectListItem> value1 = (from x in c.Cafes.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CafeName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            return View();
        }
        [HttpPost]
        public ActionResult CafeAdd(Cafe p)
        {
            c.Cafes.Add(p);
            c.SaveChanges();
            return RedirectToAction("CafeInfo");
        }

        public ActionResult CafeDelete(int id)
        {
            var value = c.Cafes.Find(id);
            value.Status = "0";
            c.SaveChanges();
            return RedirectToAction("CafeInfo");
        }
        public ActionResult CafeUpgrade(int id)
        {
            List<SelectListItem> value1 = (from x in c.Cafes.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CafeName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            var values = c.Cafes.Find(id);
            return View("CafeUpgrade", values);
        }

        public ActionResult CafeUpdate(Cafe p)
        {
            var cafe = c.Cafes.Find(p.Id);
            cafe.CafeName = p.CafeName;
            cafe.Adress = p.Adress;
            cafe.Status = p.Status;
            cafe.Explanation = p.Explanation;
            cafe.Location = p.Location;
            cafe.CoverImg = p.CoverImg;
            c.SaveChanges();

            return RedirectToAction("CafeInfo");
        }

        // Menu
        public ActionResult Menu(string p)
        {
            var list = from x in c.Menus select x;
            if (!string.IsNullOrEmpty(p))
            { list = list.Where(y => y.FoodName.Contains(p)); }
            return View(list.ToList());
        }

        [HttpGet]
        public ActionResult MenuAdd()
        {
            List<SelectListItem> value1 = (from x in c.Menus.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.FoodName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            return View();
        }
        [HttpPost]
        public ActionResult MenuAdd(Menu p)
        {
            c.Menus.Add(p);
            c.SaveChanges();
            return RedirectToAction("Menu");
        }

       
        public ActionResult MenuUpgrade(int id)
        {
            List<SelectListItem> value1 = (from x in c.Menus.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.FoodName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            var values = c.Menus.Find(id);
            return View("MenuUpgrade", values);
        }

        public ActionResult MenuUpdate(Menu p)
        {
            var cafe = c.Menus.Find(p.Id);
            cafe.FoodName = p.FoodName;
            cafe.Explanation = p.Explanation;
            cafe.Price = p.Price;
            c.SaveChanges();

            return RedirectToAction("Menu");
        }

        // Cafe Class
        public ActionResult CafeClass(string p)
        {
            var list = from x in c.CafeClasses select x;
            if (!string.IsNullOrEmpty(p))
            { list = list.Where(y => y.Type.Contains(p)); }
            return View(list.ToList());
        }

        [HttpGet]
        public ActionResult CafeClassAdd()
        {
            List<SelectListItem> value1 = (from x in c.CafeClasses.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Type,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            return View();
        }
        [HttpPost]
        public ActionResult CafeClassAdd(CafeClass p)
        {
            c.CafeClasses.Add(p);
            c.SaveChanges();
            return RedirectToAction("CafeClass");
        }


        public ActionResult CafeClassUpgrade(int id)
        {
            List<SelectListItem> value1 = (from x in c.CafeClasses.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Type,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            var values = c.CafeClasses.Find(id);
            return View("CafeClassUpgrade", values);
        }

        public ActionResult CafeClassUpdate(CafeClass p)
        {
            var cafe = c.CafeClasses.Find(p.Id);
            cafe.Type = p.Type;
            c.SaveChanges();

            return RedirectToAction("CafeClass");
        }

        // Hotel Info
        public ActionResult HotelInfo(string p)
        {
            var list = from x in c.Hotels select x;
            if (!string.IsNullOrEmpty(p))
            { list = list.Where(y => y.HotelName.Contains(p)); }
            return View(list.ToList());
        }

        [HttpGet]
        public ActionResult HotelAdd()
        {
            List<SelectListItem> value1 = (from x in c.Hotels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.HotelName,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.value1 = value1;
            return View();
        }
        [HttpPost]
        public ActionResult HotelAdd(Hotel p)
        {

PlaceSite/PlaceSite/Views/AdminPanel/AboutUpgrade.cshtml
@model PlaceSite.Models.About
@{
    ViewBag.Title = "AboutUpgrade";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Update About Info</h2>
<br />
@using (Html.BeginForm("AboutUpdate", "AdminPanel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.AboutUs);
    @Html.TextBoxFor(x => x.AboutUs, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Img);
    @Html.TextBoxFor(x => x.Img, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Update</button>
}

PlaceSite/PlaceSite/Views/AdminPanel/AdminAdd.cshtml
@model PlaceSite.Models.Admin
@{
    ViewBag.Title = "AdminAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Add To User</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.UserName);
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Password);
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Save</button>
</form>

PlaceSite/PlaceSite/Views/AdminPanel/AdminUpgrade.cshtml
@model PlaceSite.Models.Admin
@{
    ViewBag.Title = "AdminUpgrade";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Update User Info</h2>
<br />
@using (Html.BeginForm("AdminUpdate", "AdminPanel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.UserName);
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Password);
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Update</button>
}

PlaceSite/PlaceSite/Views/AdminPanel/CafeAdd.cshtml
@model PlaceSite.Models.Cafe
@{
    ViewBag.Title = "CafeAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Add To Cafe</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.CafeName);
    @Html.TextBoxFor(x => x.CafeName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adress);
    @Html.TextBoxFor(x => x.Adress, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Status);
    @Html.TextBoxFor(x => x.Status, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Explanation);
    @Html.TextBoxFor(x => x.Explanation, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Location);
    @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Star);
    @Html.TextBoxFor(x => x.Star, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.CoverImg);
    @Html.TextBoxFor(x => x.CoverImg, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Class.Id);
    @Html.TextBoxFor(x => x.Class.Id, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CafeGallery_Id);
    @Html.TextBoxFor(x => x.CafeGallery_Id, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Menu);
    @Html.TextBoxFor(x => x.Menu, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Save</button>
</form>

PlaceSite/PlaceSite/Views/AdminPanel/CafeClass.cshtml
@using PlaceSite.Models;
@model List<CafeClass>
@{
    ViewBag.Title = "CafeClass";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Class Name</th>

    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.Id</td>
            <td>@u.Type</td>
            <td> <a href="/AdminPanel/CafeClassDelete/@u.Id" class="btn btn-danger">Delete</a></td>
            <td> <a href="/AdminPanel/CafeClassUpgrade/@u.Id" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/AdminPanel/CafeClassAdd/" class="btn btn-info">Add To Cafe</a>

PlaceSite/PlaceSite/Views/AdminPanel/CafeClassAdd.cshtml
@model PlaceSite.Models.CafeClass

@{
    ViewBag.Title = "CafeClassAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Add To Cafe Class</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.Type);
    @Html.TextBoxFor(x => x.Type, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Save</button>
</form>

PlaceSite/PlaceSite/Views/AdminPanel/CafeClassUpgrade.cshtml
@model PlaceSite.Models.CafeClass

@{
    ViewBag.Title = "CafeClassUpgrade";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Update Cafe Class Info</h2>
<br />
@using (Html.BeginForm("CafeClassUpdate", "AdminPanel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.Type);
    @Html.TextBoxFor(x => x.Type, new { @class = "form-control" })
    <br />
  
    <button class="btn btn-warning">Update</button>
}

PlaceSite/PlaceSite/Views/AdminPanel/HotelClass.cshtml
@using PlaceSite.Models;
@model List<HotelClass>
@{
    ViewBag.Title = "HotelClass";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Class Name</th>

    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.Id</td>
            <td>@u.Type</td>
            <td> <a href="/AdminPanel/HotelClassDelete/@u.Id" class="btn btn-danger">Delete</a></td>
            <td> <a href="/AdminPanel/HotelClassUpgrade/@u.Id" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/AdminPanel/HotelClassAdd/" class="btn btn-info">Add To Hotel Class</a>

PlaceSite/PlaceSite/Views/AdminPanel/HotelClassAdd.cshtml
@model PlaceSite.Models.HotelClass

@{
    ViewBag.Title = "HotelClassAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Add To Hotel Class</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.Type);
    @Html.TextBoxFor(x => x.Type, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Save</button>
</form>

PlaceSite/PlaceSite/Views/AdminPanel/HotelClassUpgrade.cshtml
@model PlaceSite.Models.HotelClass
@{
    ViewBag.Title = "HotelClassUpgrade";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Update Hotel Class</h2>
<br />
@using (Html.BeginForm("HotelClassUpdate", "AdminPanel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.Type);
    @Html.TextBoxFor(x => x.Type, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Update</button>
}

PlaceSite/PlaceSite/Views/AdminPanel/HotelUpgrade.cshtml
@model PlaceSite.Models.Hotel

@{
    ViewBag.Title = "HotelUpgrade";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Update Hotel Info</h2>
<br />
@using (Html.BeginForm("HotelUpdate", "AdminPanel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.HotelName);
    @Html.TextBoxFor(x => x.HotelName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adress);
    @Html.TextBoxFor(x => x.Adress, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Status);
    @Html.TextBoxFor(x => x.Status, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Explanation);
    @Html.TextBoxFor(x => x.Explanation, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Location);
    @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Star);
    @Html.TextBoxFor(x => x.Star, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CoverImg);
    @Html.TextBoxFor(x => x.CoverImg, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Update</button>
}

PlaceSite/PlaceSite/Views/AdminPanel/MenuAdd.cshtml
@model PlaceSite.Models.Menu
@{
    ViewBag.Title = "MenuAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Add To Menu</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.FoodName);
    @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Explanation);
    @Html.TextBoxFor(x => x.Explanation, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price);
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
  
    <button class="btn btn-primary">Save</button>
</form>

PlaceSite/PlaceSite/Views/AdminPanel/MenuUpgrade.cshtml
@model PlaceSite.Models.Menu
@{
    ViewBag.Title = "MenuUpgrade";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Update Menu Info</h2>
<br />
@using (Html.BeginForm("MenuUpdate", "AdminPanel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)

    @Html.LabelFor(x => x.FoodName);
    @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Explanation);
    @Html.TextBoxFor(x => x.Explanation, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price);
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Update</button>
}

PlaceSite/PlaceSite/Views/AdminPanel/Price.cshtml
@using PlaceSite.Models;
@model List<Price>
@{
    ViewBag.Title = "Price";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Room Name</th>
        <th>Price</th>

    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.RoomName</td>
            <td>@u.RoomPrice</td>
            <td> <a href="/AdminPanel/PriceDelete/@u.Id" class="btn btn-danger">Delete</a></td>
            <td> <a href="/AdminPanel/PriceUpgrade/@u.Id" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/AdminPanel/PriceAdd/" class="btn btn-info">Add To Cafe</a>